# -*- coding: utf-8 -*-
"""decarton-ia-prompt(SINKEY).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aId5KhPF1jIPEXqt_5ixZAUQrbjV_9F2
"""

import openai

openai.api_key = "KEY"

# texto
def generar_texto(prompt, max_tokens=150):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "Eres un experto en sostenibilidad y economía circular."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=max_tokens,
            temperature=0.7
        )
        return response['choices'][0]['message']['content'].strip()
    except Exception as e:
        return f"Error generando texto: {str(e)}"

# imagen
def generar_imagen(prompt, size="1024x1024"):
    try:
        response = openai.Image.create(
            prompt=prompt,
            n=1,
            size=size
        )
        return response['data'][0]['url']
    except Exception as e:
        return f"Error generando imagen: {str(e)}"

# Ejecucion
texto_prompt = "Explica cómo la segregación de residuos potencia la economía circular en pymes."
imagen_prompt = "Diseña una ilustración del ciclo de reciclaje de cartón desde su recolección hasta su transformación."

texto = generar_texto(texto_prompt)
print("Texto generado:\n", texto)

imagen_url = generar_imagen(imagen_prompt)
print("URL de la imagen generada:\n", imagen_url)

